feat: automatic use-setup-gradle and SBOM generation (#82)
feat: Submit dependency graph to Github on merge/push to default branch
feat: Simplify steps by converting some python code to equivalent bash
chore: Rename steps for readability and consistency
docs: Update documentation to reflect deprecation of the use_setup_gradle option
chore: "Bump" setup-gradle version to follow major v4

diff --git a/.github/workflows/code-scan.yml b/.github/workflows/code-scan.yml
--- a/.github/workflows/code-scan.yml
+++ b/.github/workflows/code-scan.yml
@@ -4,7 +4,7 @@ on:
   workflow_call:
     inputs:
       use_setup_gradle:
-        description: 'Use "gradle/action/setup-gradle" before running autobuild (Java/Kotlin only). Potentially speeds up build times if cache from main branch is utilized'
+        description: 'OBSOLETE. This is now autodetected and enabled if `build.gradle(.kt(s))` is found. Uses "gradle/action/setup-gradle" before running autobuild (Java/Kotlin only). Potentially speeds up build times if cache from main branch is utilized'
         default: false
         required: false
         type: boolean
@@ -31,7 +31,7 @@ env:
   GITHUB_REPOSITORY: ${{ github.repository }}
 
 jobs:
-  input_validation:
+  input-validation:
     runs-on: ubuntu-24.04
     steps:
       - name: "Validate inputs"
@@ -75,121 +75,50 @@ jobs:
             exit(1)
           
           os.system('echo Validation passed')"
-  upload-scan-reports-from-matching-pr:
+  upload-cached-results:
     runs-on:  ubuntu-24.04
-    needs: input_validation
+    needs: input-validation
     outputs:
       skip_job_and_continue_scan: ${{ env.GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN }}
     permissions:
       pull-requests: read
       actions: read
       security-events: write
-      contents: read
+      contents: write 
     steps:
       - name: "Skip job if not triggered by a push to main/master"
         env:
           GITHUB_EVENT_NAME: ${{ github.event_name }}
-          GITHUB_REF: ${{ github.ref }}
+          GITHUB_REFNAME: ${{ github.ref_name }}
+          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
         run: |
-          python -c "
-          import os
-
-          skip_job_and_continue_scan = False
-
-          env_file = os.getenv('GITHUB_ENV')
-          github_event_name = os.getenv('GITHUB_EVENT_NAME')
-          github_ref = os.getenv('GITHUB_REF')
-
-          if github_event_name != 'push' or (github_ref != 'refs/heads/main' and github_ref != 'refs/heads/master'):
-            skip_job_and_continue_scan = True
-
-          with open(env_file, 'a') as f:
-            f.write('GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=' + str(skip_job_and_continue_scan) + '\n')
-          "
+          if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$GITHUB_REFNAME" = "$GITHUB_DEFAULT_BRANCH" ]; then
+            echo 'GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=False' >> $GITHUB_ENV
+          else
+            echo 'GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=True' >> $GITHUB_ENV
+          fi
       - name: "Get workflow run ID for matching PR"
         if: ${{ env.GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN == 'False' }}
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_SHA: ${{ github.sha }}
         run: |
-          python -c "
-          import os
-          import requests
+          HEAD_REF=$(gh pr list --state merged --search "$GITHUB_SHA" --json headRefOid -R $GITHUB_REPOSITORY | jq -r '.[0].headRefOid')
+          if [ "$HEAD_REF" = "null" ]; then
+            echo "::warning ::Failed to fetch closed PRs, defaulting to running a new scan"
+            echo 'GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=True' >> $GITHUB_ENV
+          else
+            JOB_ID=$(gh run list -s completed -e pull_request -c "$HEAD_REF" --json databaseId -R $GITHUB_REPOSITORY -w ".github/workflows/codeql.yml" | 
+              jq -r '.[0].databaseId')
+            if [ "$JOB_ID" = "null" ]; then
+              echo '::warning ::Failed to find a matching job, defaulting to running a new scan'
+              echo 'GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=True' >> $GITHUB_ENV
+            else
+              echo "GHA_SECURITY_CODE_SCAN_WORKFLOW_RUN_ID=$JOB_ID" >> $GITHUB_ENV
+            fi
+          fi
 
-          skip_job_and_continue_scan = False
-
-          github_sha = os.getenv('GITHUB_SHA')
-          github_token = os.getenv('GITHUB_TOKEN')
-          github_repository = os.getenv('GITHUB_REPOSITORY')
-          env_file = os.getenv('GITHUB_ENV')
-
-          headers = {
-            'Accept': 'application/vnd.github+json',
-            'X-GitHub-Api-Version': '2022-11-28',
-            'Authorization': f'token {github_token}'
-          }
-              
-          five_recently_updated_closed_prs = requests.get(
-            f'https://api.github.com/repos/{github_repository}/pulls',
-            headers=headers,
-            params={
-              'state': 'closed',
-              'per_page': '5',
-              'sort': 'updated',
-              'direction': 'desc'
-            }
-          )
-          
-          if five_recently_updated_closed_prs.status_code != 200:
-            print('::warning ::Failed to fetch closed PRs, defaulting to running a new scan')
-            skip_job_and_continue_scan = True
-          else: 
-            five_recently_updated_closed_prs = five_recently_updated_closed_prs.json()
-            pr_head = None
-            for closed_pr in five_recently_updated_closed_prs:
-              merge_commit_sha = closed_pr.get('merge_commit_sha')
-              if merge_commit_sha == github_sha:
-                pr_head = closed_pr.get('head').get('sha')
-                break
-              
-            if pr_head != None:
-              workflow_runs = requests.get(
-                f'https://api.github.com/repos/{github_repository}/actions/runs',
-                headers=headers,
-                params={
-                  'head_sha': pr_head,
-                  'event': 'pull_request',
-                  'status': 'completed'
-                }
-              )
-
-              if workflow_runs.status_code != 200:
-                print('::warning ::Failed to fetch PR workflow runs, defaulting to running a new scan')
-                skip_job_and_continue_scan = True
-              else:
-                workflow_runs = workflow_runs.json().get('workflow_runs', [])
-                run_id = None
-                for workflow_run in workflow_runs:
-                  if workflow_run.get('path','').startswith('.github/workflows/codeql.yml'):
-                    run_id = workflow_run.get('id')
-                    
-                    with open(env_file, 'a') as f:
-                      f.write(f'GHA_SECURITY_CODE_SCAN_WORKFLOW_RUN_ID={run_id}\n')
-                    
-                    break
-                if run_id is None:
-                  print('::warning ::Failed to find a matching workflow run on the PR, defaulting to running a new scan')
-                  skip_job_and_continue_scan = True
-                
-            else:
-              print('::warning ::Failed to fetch a matching PR, defaulting to running a new scan')
-              skip_job_and_continue_scan = True
-
-          with open(env_file, 'a') as f:
-            f.write('GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=' + str(skip_job_and_continue_scan) + '\n')
-          "
-
-      - name: "Download existing scan reports from workflow run ID"
+      - name: "Download existing cached results from previous job (pr)"
         if: ${{ env.GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN == 'False' }}
         uses: actions/download-artifact@v4
         with:
@@ -197,23 +126,50 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           path: "/home/runner/work/${{ env.GITHUB_REPOSITORY }}/results"
 
-      - name: "Upload scan reports to Security tab"
+      - name: "Upload scan results"
         if: ${{ env.GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN == 'False' }}
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: "/home/runner/work/${{ env.GITHUB_REPOSITORY }}/results"
           category: 'scan-results'
 
-  get-repository-languages:
-    if: ${{ needs.upload-scan-reports-from-matching-pr.outputs.skip_job_and_continue_scan == 'True' }}
+      - name: "Upload dependency graph"
+        if: ${{ env.GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN == 'False' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_SHA: ${{ github.sha }}
+          GITHUB_REF: ${{ github.ref }}
+        run: |
+          shopt -s globstar
+          for file in /home/runner/work/$GITHUB_REPOSITORY/results/**/*.json ; do
+            if [ -d $file ] ; then
+              continue
+            fi
+            jq ".sha = \"$GITHUB_SHA\" | .ref = \"$GITHUB_REF\"" <$file | 
+              gh api /repos/$GITHUB_REPOSITORY/dependency-graph/snapshots --method POST --input -
+          done
+
+  get-repository-metadata:
+    if: ${{ needs.upload-cached-results.outputs.skip_job_and_continue_scan == 'True' }}
     runs-on: ubuntu-24.04
-    needs: upload-scan-reports-from-matching-pr
+    needs: upload-cached-results
     outputs: 
       codeql_languages: ${{ env.GHA_SECURITY_CODE_SCAN_REPOSITORY_LANGUAGES_CQ }}
       semgrep_languages: ${{ env.GHA_SECURITY_CODE_SCAN_REPOSITORY_LANGUAGES_SEM }} 
+      found_gradle: ${{ env.GHA_SECURITY_CODE_SCAN_FOUND_GRADLE }}
     steps:
       - name: "Checkout repository"
         uses: actions/checkout@v4
+
+      - name: "Find Gradle Build"
+        id: find-gradle-build
+        run: |
+          # Search for the file(s) build.gradle or build.gradle.kt(s) in the repo, and report if any of those are found
+          if [ $(find . -type f -iname build.gradle -o -iname build.gradle.kts -o -iname build.gradle.kt | wc -l) -gt 0 ]; then
+            echo "GHA_SECURITY_CODE_SCAN_FOUND_GRADLE=True" >> $GITHUB_ENV
+          else
+            echo "GHA_SECURITY_CODE_SCAN_FOUND_GRADLE=False" >> $GITHUB_ENV
+          fi
 
       - name: "Get repository languages"
         id: get-repository-languages
@@ -321,9 +277,9 @@ jobs:
   semgrep-analysis:
     # See https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#scanning-on-push
     # If we found a language, and the event is not a push made by dependabot on a PR
-    if: ${{ needs.get-repository-languages.outputs.semgrep_languages != '[]' && (github.event != 'push' || (github.event == 'push' && github.actor != 'dependabot[bot]')) }}
+    if: ${{ needs.get-repository-metadata.outputs.semgrep_languages != '[]' && (github.event != 'push' || (github.event == 'push' && github.actor != 'dependabot[bot]')) }}
     runs-on: ubuntu-24.04
-    needs: get-repository-languages
+    needs: get-repository-metadata
     permissions:
       # Semgrep - required for all workflows
       security-events: write
@@ -333,7 +289,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        language: ${{ fromJson(needs.get-repository-languages.outputs.semgrep_languages) }}
+        language: ${{ fromJson(needs.get-repository-metadata.outputs.semgrep_languages) }}
     steps:
       - name: "Checkout repository"
         uses: actions/checkout@v4
@@ -384,30 +340,31 @@ jobs:
   codeql-analysis:
     # See https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#scanning-on-push
     # If we found a language, and the event is not a push made by dependabot on a PR
-    if: ${{ needs.get-repository-languages.outputs.codeql_languages != '[]' && (github.event != 'push' || (github.event == 'push' && github.actor != 'dependabot[bot]')) }}
+    if: ${{ needs.get-repository-metadata.outputs.codeql_languages != '[]' && (github.event != 'push' || (github.event == 'push' && github.actor != 'dependabot[bot]')) }}
     # Runners are selected by labels: (default when you pass a string directly to runs-on) or group: "grp-runner". This snippet of code uses JSON to construct the group: object if the runner name starts with "grp-"
     runs-on:  ${{ startsWith(inputs.job_runner, 'grp-') && fromJSON(format('{{"group":"{0}"}}', inputs.job_runner)) || inputs.job_runner }}
-    needs: get-repository-languages
+    needs: get-repository-metadata
     permissions:
       # CodeQL - required for all workflows
       security-events: write
       # CodeQL - only required for workflows in private repositories
       actions: read
-      contents: read
+      contents: write
     strategy:
       fail-fast: false
       matrix:
-        language: ${{ fromJson(needs.get-repository-languages.outputs.codeql_languages) }}
+        language: ${{ fromJson(needs.get-repository-metadata.outputs.codeql_languages) }}
     steps:
       - name: "Checkout repository"
         uses: actions/checkout@v4
 
       - name: "Set up Gradle for Java/Kotlin"
-        if: inputs.use_setup_gradle && (matrix.language == 'kotlin' || matrix.language == 'java')
-        uses: gradle/actions/setup-gradle@v4.1.0
+        if: needs.get-repository-metadata.outputs.found_gradle == 'True' && (matrix.language == 'kotlin' || matrix.language == 'java')
+        uses: gradle/actions/setup-gradle@v4
         with: 
           cache-read-only: true  # Force read only, even in main
           add-job-summary: 'on-failure'
+          dependency-graph: ${{ github.ref_name == github.event.repository.default_branch && 'generate-submit-and-upload' || 'generate-and-upload' }}
 
       - name: "Initialize CodeQL for Java/Kotlin"
         if: matrix.language == 'kotlin' || matrix.language == 'java'
