feat: add notifications to docker and code scanner

diff --git a/.github/workflows/code-scan.yml b/.github/workflows/code-scan.yml
--- a/.github/workflows/code-scan.yml
+++ b/.github/workflows/code-scan.yml
@@ -29,6 +29,7 @@ on:
         required: false
 env:
   GITHUB_REPOSITORY: ${{ github.repository }}
+  GIT_REF: ${{ github.ref }}
 
 jobs:
   input-validation:
@@ -407,7 +408,7 @@ jobs:
           path: "/home/runner/work/${{ env.REPOSITORY_NAME }}/results"
           overwrite: true
 
-  allowlist-code-scan-alerts:
+  run-scanner-action:
     needs: [codeql-analysis, semgrep-analysis]
     if: |
       always() && 
@@ -418,22 +419,27 @@ jobs:
       security-events: write
       # required to checkout the repository
       contents: read
+    outputs:
+      notification_severity_threshold: ${{ steps.scanner-action.outputs.notification_severity_threshold }}
+      notification_slack_channel_id: ${{ steps.scanner-action.outputs.notification_slack_channel_id }}
+      notification_slack_enabled: ${{ steps.scanner-action.outputs.notification_slack_enabled }}
+      notification_pull_request_enabled: ${{ steps.scanner-action.outputs.notification_pull_request_enabled }}
     steps:
       - name: "Checkout repository"
         uses: actions/checkout@v4
       
       - name: Scanner Action
+        id: scanner-action
         uses: entur/gha-security/scanner-action@v2
         with:
           scanner: 'codescan'
           token: ${{ secrets.GITHUB_TOKEN }}
           external-repository-token: ${{ secrets.external_repository_token }}
 
-
   check-for-critical-alerts:
     runs-on: ubuntu-24.04
     if: ${{ always() }}
-    needs: [allowlist-code-scan-alerts]
+    needs: [run-scanner-action]
     permissions: 
       security-events: read # required to read code scan alerts
       issues: write # required for creating issues, and/or adding issue comments
@@ -450,7 +456,7 @@ jobs:
           -H 'Accept: application/vnd.github+json' \
           -H 'X-GitHub-Api-Version: 2022-11-28' \
           /repos/${GITHUB_REPOSITORY}/code-scanning/alerts \
-          -F severity="$1" -F state='open' -F ref='${{ github.ref }}' -F per_page='100' -F tool_name="$2" --paginate)"
+          -F severity="$1" -F state='open' -F ref='$GIT_REF' -F per_page='100' -F tool_name="$2" --paginate)"
           alerts_exit_code=$? # Save exit code from gh api command
         }
         get_alerts "error" "Semgrep OSS"
@@ -477,7 +483,6 @@ jobs:
       if: ${{ env.GHA_SECURITY_CODE_SCAN_CREATE_ALERT_COMMENT == 'True' }}
       env:
         REPOSITORY: ${{ github.repository }}
-        GIT_REF: ${{ github.ref }}
       run: |
         echo '## ⛔ Code Scan - Critical Vulnerabilities ⛔
         **Code scan detected critical vulnerabilities in the code that needs to be addressed.**
@@ -491,11 +496,73 @@ jobs:
       if: ${{ env.GHA_SECURITY_CODE_SCAN_CREATE_ALERT_COMMENT == 'True' && github.event_name == 'pull_request' }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        PR_NUMBER: ${{ github.event.pull_request.number }}
       run: |
-        gh pr comment ${{ github.event.pull_request.number }} --repo $GITHUB_REPOSITORY -b "## ⛔ Code Scan - Critical Vulnerabilities ⛔
+        gh pr comment $PR_NUMBER --repo $GITHUB_REPOSITORY -b "## ⛔ Code Scan - Critical Vulnerabilities ⛔
         **Code scan found critical vulnerabilities in the code that needs to be addressed.**
         ### Results
-        The scan results can be found [here](https://github.com/${GITHUB_REPOSITORY}/security/code-scanning?query=is%3Aopen+pr%3A${{ github.event.pull_request.number }})
+        The scan results can be found [here](https://github.com/${GITHUB_REPOSITORY}/security/code-scanning?query=is%3Aopen+pr%3A$PR_NUMBER)
         ### Allowlist
         Use the allowlist if you want to ignore vulnerabilities that do not affect the repository.  
         See the [Code Scan documentation](https://github.com/entur/gha-security/blob/main/README-code-scan.md#allow-lists) on how to use allowlist."
+        
+  notifications:
+    needs: [ run-scanner-action ]
+    runs-on: ubuntu-24.04
+    steps:
+      - name: "Check alerts"
+        id: check-alerts
+        env:
+          SEVERITY_THRESHOLD: ${{ run-scanner-action.outputs.notification_severity_threshold }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set +e # Do not exit if a command fails
+          get_alerts () {
+            alerts="$(gh api \
+            --method GET \
+            -H 'Accept: application/vnd.github+json' \
+            -H 'X-GitHub-Api-Version: 2022-11-28' \
+            /repos/${GITHUB_REPOSITORY}/code-scanning/alerts \
+            -F severity="$1" -F state='open' -F ref='${{ github.ref }}' -F per_page='100' -F tool_name="$2" --paginate)"
+            alerts_exit_code=$? # Save exit code from gh api command
+          }
+          
+          get_alerts "$SEVERITY_THRESHOLD" "CodeQL"
+          
+          if [ "$alerts" == "[]" ]; then
+            echo 'ALERTS_FOUND='False >> $GITHUB_OUTPUT
+          else
+            echo 'ALERTS_FOUND='True >> $GITHUB_OUTPUT
+          fi
+      - name: "Notification message"
+        id: notification-message
+        if: ${{ steps.check-alerts.outputs.ALERTS_FOUND == 'True' }}
+        env:
+          SEVERITY_THRESHOLD: ${{ run-scanner-action.outputs.notification_severity_threshold }}
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+        run: |
+          {
+            echo "NOTIFICATION_MESSAGE<<EOF"
+            echo "## Code Scan - $SEVERITY_THRESHOLD Alert(s) found
+          ### Results
+          The scan results can be found [here](https://github.com/${GITHUB_REPOSITORY}/security/code-scanning?query=is%3Aopen+pr%3A$PR_NUMBER)
+          ### Allowlist
+          Use the allowlist if you want to ignore vulnerabilities that do not affect the repository.
+          See the [Code Scan documentation](https://github.com/entur/gha-security/blob/main/README-code-scan.md#allow-lists) on how to use allowlist."
+            echo EOF
+          } >> "$GITHUB_OUTPUT"
+
+      - name: "Pull Request notification output"
+        if: ${{ steps.check-alerts.outputs.ALERTS_FOUND == 'True' && run-scanner-action.outputs.notification_pull_request_enabled == 'True' }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NOTIFICATION_MESSAGE: ${{ steps.notification-message.outputs.NOTIFICATION_MESSAGE }}
+        run: |
+          gh pr comment $PR_NUMBER --repo $GITHUB_REPOSITORY -b $NOTIFICATION_MESSAGE
+      - name: "Slack notification output"
+        uses: entur/gha-slack/.github/workflows/post.yml@v2
+        if: ${{ steps.check-alerts.outputs.ALERTS_FOUND == 'True' && run-scanner-action.outputs.notification_slack_enabled == 'True' }}
+        with:
+          channel_id: ${{ run-scanner-action.outputs.notification_slack_channel_id }}
+          message: ${{ steps.notification-message.outputs.NOTIFICATION_MESSAGE }}
+          secrets: inherit
