feat: add codeql kotlin support warning (#233)
* feat: add codeql kotlin support warning

* test: codeql kotlin error handler

* chore: remove extra empty lines

* chore: add documentation, and runner os check

* test: add assert step

* test: fix wrong variable

* test: remove temp assert test

* chore: fix failing actionlint check

* fix: should be able to extract beta versions with regex

* test: fix missing should-fail

* fix: use gha-security @v2 for codeql-ktolin-error-handler

* fix: include actions path in uses for codeql-kotlin-error-handler

diff --git a/.github/workflows/test-actions.yml b/.github/workflows/test-actions.yml
--- a/.github/workflows/test-actions.yml
+++ b/.github/workflows/test-actions.yml
@@ -95,8 +95,45 @@ jobs:
               script: |
                 const assertSarifFix = require("./.github/test-scripts/assert-sarif-fix.js");
                 assertSarifFix({ core });
-
-
+    test-codeql-kotlin-error-handler:
+      runs-on: ubuntu-24.04
+      name: ${{ matrix.test.title }}
+      strategy:
+          matrix:
+              test:
+                - title: "Should fail with Kotlin support error"
+                  log-message: "Kotlin version 2.4.0 is too recent. CodeQL currently supports versions below 2.3.30\n ..."
+                  should-fail: true
+                - title: "Should silently exit if no Kotlin support error"
+                  log-message: "No errors found here!"
+                  should-fail: false
+                - title: "Should fail with Kotlin support error when using Beta version"
+                  log-message: "Kotlin version 2.4.20-Beta1 is too recent. CodeQL currently supports versions below 2.3.30\n ..."
+                  should-fail: true
+      steps:
+        - name: "Checkout repository"
+          uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.2
+          with:
+            persist-credentials: false
+        - name: "Log message"
+          env:
+            LOG_MESSAGE: ${{ matrix.test.log-message }}
+          run: |
+            echo "$LOG_MESSAGE"
+        - name: "CodeQL Kotlin error handler"
+          id: codeql-kotlin-error-handler
+          continue-on-error: ${{ matrix.test.should-fail }}
+          uses: ./.github/actions/codeql-kotlin-error-handler
+        - name: "Assert step outcome"
+          if: ${{ matrix.test.should-fail && steps.codeql-kotlin-error-handler.outcome != 'failure' }}
+          env:
+            EXPECTED_OUTCOME: ${{ matrix.test.should-fail && 'failure' || 'success'  }}
+            STEP_OUTCOME: ${{ steps.codeql-kotlin-error-handler.outcome }}
+          run: |
+            echo "::error::Assert failed: expected step outcome to be $EXPECTED_OUTCOME but actual outcome is $STEP_OUTCOME"
+            exit 1;
+            
+            
     test-dynamic-secrets:
       runs-on: ubuntu-24.04
       name: ${{ matrix.test.title }}
